
on:
  workflow_dispatch:

env:
  MY_VAR: workflow

jobs:
  variables:
    runs-on: ubuntu-latest
    env:
      MY_VAR: jobs
    steps:
      - name: Print
        run: |
          echo "${{ secrets.PASSWORD }}"
        env:
          MY_VAR: steps
